<script>
/* ═══════════════════════════════════════════════════════════════════
   DÁTA — certifikácie, projekty, slovník, flashcards, kariéra,
   achievementy a scenáre AI mentora
   ═══════════════════════════════════════════════════════════════════ */

/* ── CERTIFIKÁCIE ─────────────────────────────────────────────────
   readiness: moduly a min. % progresu odporúčané pred skúškou */
DATA.certs = [
  { id: 'cert-search', name: 'Google Ads Search Certification', module: 'ads',
    url: 'https://skillshop.exceedlms.com/student/catalog', official: 'Google Skillshop',
    desc: 'Základná a najžiadanejšia certifikácia — vyhľadávacie kampane, aukcia, kľúčové slová, RSA, bidding. Toto je certifikát, ktorý agentúry vyžadujú ako prvý.',
    difficulty: 'Stredná', validity: '12 mesiacov', questions: '~50 otázok', time: '75 minút', passing: '80 %',
    knowledge: ['Ad Rank a aukcia', 'Match types a negatívne slová', 'RSA a assets', 'Smart Bidding', 'Meranie konverzií'],
    checklist: ['Dokončený modul Google Ads – sekcie 1, 2 a 4', 'Mock test v aplikácii na 80 %+', 'Prejdený Skillshop study path Search', 'Rozumiem „Google-recommended" logike odpovedí'],
    reqModules: { ads: 60 } },
  { id: 'cert-display', name: 'Google Ads Display Certification', module: 'ads',
    url: 'https://skillshop.exceedlms.com/student/catalog', official: 'Google Skillshop',
    desc: 'Display sieť — publiká, responsive display ads, ochrana značky, awareness metriky.',
    difficulty: 'Ľahšia', validity: '12 mesiacov', questions: '~50 otázok', time: '75 minút', passing: '80 %',
    knowledge: ['Typy publík (affinity, in-market, custom)', 'Responsive Display Ads', 'Placement exclusions', 'Frequency capping'],
    checklist: ['Dokončená lekcia Display kampane', 'Dokončená sekcia Publiká a remarketing', 'Mock test na 80 %+'],
    reqModules: { ads: 50 } },
  { id: 'cert-video', name: 'Google Ads Video Certification', module: 'ads',
    url: 'https://skillshop.exceedlms.com/student/catalog', official: 'Google Skillshop',
    desc: 'YouTube reklama — formáty, ABCD framework kreatívy, brand lift, video action kampane.',
    difficulty: 'Stredná', validity: '12 mesiacov', questions: '~50 otázok', time: '75 minút', passing: '80 %',
    knowledge: ['Video formáty a platobné modely', 'ABCD framework', 'Cielenie na YouTube', 'Awareness metriky'],
    checklist: ['Dokončená lekcia Video kampane', 'Rozumiem CPV vs. CPM modelom', 'Mock test na 80 %+'],
    reqModules: { ads: 50 } },
  { id: 'cert-shopping', name: 'Shopping Ads Certification', module: 'ads',
    url: 'https://skillshop.exceedlms.com/student/catalog', official: 'Google Skillshop',
    desc: 'Produktové reklamy — Merchant Center, feed optimalizácia, Shopping a PMax retail.',
    difficulty: 'Stredná', validity: '12 mesiacov', questions: '~50 otázok', time: '75 minút', passing: '80 %',
    knowledge: ['Merchant Center a feed atribúty', 'Title optimalizácia', 'Dôvody suspendácií', 'PMax s feedom'],
    checklist: ['Dokončená lekcia Shopping a Merchant Center', 'Dokončená lekcia Performance Max', 'Mock test na 80 %+'],
    reqModules: { ads: 55 } },
  { id: 'cert-measure', name: 'Google Ads Measurement Certification', module: 'ads',
    url: 'https://skillshop.exceedlms.com/student/catalog', official: 'Google Skillshop',
    desc: 'Meranie a atribúcia — konverzné tagy, Enhanced Conversions, Consent Mode, data-driven atribúcia. Najužitočnejšia certifikácia pre prax.',
    difficulty: 'Ťažšia', validity: '12 mesiacov', questions: '~50 otázok', time: '75 minút', passing: '80 %',
    knowledge: ['Konverzné meranie (tag, GA4 import)', 'Enhanced a offline conversions', 'Consent Mode v2', 'DDA atribúcia'],
    checklist: ['Dokončená sekcia Bidding a meranie', 'Rozumiem primary vs. secondary konverziám', 'Mock test na 80 %+'],
    reqModules: { ads: 65 } },
  { id: 'cert-aipower', name: 'AI-Powered Performance Ads Certification', module: 'ads',
    url: 'https://skillshop.exceedlms.com/student/catalog', official: 'Google Skillshop',
    desc: 'Automatizácia a AI — Performance Max, smart bidding, broad match stratégie, value-based bidding.',
    difficulty: 'Stredná', validity: '12 mesiacov', questions: '~50 otázok', time: '75 minút', passing: '80 %',
    knowledge: ['Performance Max do hĺbky', 'Smart Bidding stratégie', 'Broad match + automatizácia', 'Value-based bidding'],
    checklist: ['Dokončené lekcie PMax a Bidding', 'Dokončený celý modul Ads odporúčaný', 'Mock test na 80 %+'],
    reqModules: { ads: 70 } },
  { id: 'cert-analytics', name: 'Google Analytics (GA4) Certification', module: 'gsc',
    url: 'https://skillshop.exceedlms.com/student/catalog', official: 'Google Skillshop',
    desc: 'GA4 — eventy, konverzie, reporty, prepojenie s Ads. Nie je súčasťou kurzu do hĺbky, ale výborne dopĺňa GSC a Ads meranie.',
    difficulty: 'Stredná', validity: '12 mesiacov', questions: '~50 otázok', time: '75 minút', passing: '80 %',
    knowledge: ['Event model GA4', 'Key events a konverzie', 'Prepojenie s Ads', 'Reporty a explorácie'],
    checklist: ['Dokončený modul GSC (meranie súvisí)', 'Dokončená lekcia Meranie konverzií v Ads', 'Samoštúdium GA4 na Skillshop'],
    reqModules: { gsc: 70, ads: 40 } },
];

/* ── PRAKTICKÉ PROJEKTY ─────────────────────────────────────────── */
DATA.projects = [
  { id: 'proj-gbp-opt', name: 'Optimalizuj Google Business Profile', module: 'gbp', icon: 'map-pin', xp: 300,
    goal: 'Kompletná optimalizácia reálneho GBP profilu od auditu po obsahový plán.',
    brief: 'Vyber reálnu lokálnu firmu. Vykonaj audit profilu, oprav základy (kategórie, NAP, hodiny, popis), navrhni produkty/služby, priprav obsahový plán (Posts, Q&A) a systém získavania recenzií. Výstup: dokument s pred/po stavom a akčným plánom.',
    checklist: ['Audit profilu (6 oblastí)', 'Kategórie podľa konkurenčnej analýzy', 'NAP konzistencia overená', 'Services + min. 5 Products navrhnutých', '4 Google Posts pripravené', '10 Q&A párov', 'Review akvizičný plán + QR/link', 'Šablóny odpovedí na recenzie', 'Dokument pred/po + akčný plán 7/30/90'] },
  { id: 'proj-gsc-audit', name: 'Audit Search Console', module: 'gsc', icon: 'search-check', xp: 300,
    goal: 'Kompletný technický audit webu s prioritizovanými nálezmi.',
    brief: 'Vyber web (ideálne s prístupom do GSC). Prejdi 8 oblastí auditu: indexácia, robots/sitemap, architektúra, duplicity, obsah, CWV, odkazy, bezpečnosť. Zdokumentuj min. 10 nálezov s dôkazmi, závažnosťou a riešením. Výstup: audit report s plánom 30/60/90.',
    checklist: ['robots.txt a sitemap skontrolované', 'Page indexing analýza s trendmi', 'Canonical a duplicitná analýza', 'CWV field data vyhodnotené', 'Interné odkazy dôležitých stránok', 'Min. 10 nálezov s dôkazmi', 'Prioritizácia P0–P2', 'Plán 30/60/90 dní', 'Exekutívne zhrnutie'] },
  { id: 'proj-ads-account', name: 'Navrhni Google Ads účet', module: 'ads', icon: 'megaphone', xp: 400,
    goal: 'Kompletný strategický návrh Ads účtu pre reálnu firmu.',
    brief: 'Discovery (marža → cieľové CPA/ROAS), keyword research 50+ slov, návrh štruktúry kampaní, 2 kompletné RSA, plán merania s Consent Mode, launch plán a mock report. Výstup: strategický dokument, aký agentúry predávajú za stovky eur.',
    checklist: ['Discovery s ekonomikou (CPA/ROAS výpočet)', 'Keyword research 50+ slov v skupinách', 'Konkurenčná analýza SERP', 'Schéma štruktúry účtu', '2× kompletné RSA (15+4)', 'Assets návrh', 'Negatívne zoznamy', 'Plán merania + Consent Mode', 'Launch plán s očakávaniami', 'Mock mesačný report'] },
  { id: 'proj-pmax', name: 'Optimalizuj Performance Max', module: 'ads', icon: 'zap', xp: 250,
    goal: 'Návrh optimalizácie PMax kampane e-shopu.',
    brief: 'Zober (reálny alebo modelový) e-shop s PMax kampaňou. Navrhni: audit feedu (titles, GTIN, obrázky), segmentáciu asset groups podľa marže/kategórií, brand exclusions, audience signals, tROAS ciele per segment a merací plán inkrementality.',
    checklist: ['Feed audit s konkrétnymi opravami titles', 'Asset groups podľa kategórií/marže', 'Brand vylúčený z PMax', 'Audience signals navrhnuté', 'Rôzne tROAS ciele podľa marže', 'Návrh testu inkrementality', 'Zoznam KPI na vyhodnotenie'] },
  { id: 'proj-web-errors', name: 'Nájdi chyby vo webe', module: 'gsc', icon: 'bug', xp: 200,
    goal: 'Rýchla technická diagnostika — nájdi 10 chýb za 60 minút.',
    brief: 'Šprint: vyber ľubovoľný stredne veľký web a za hodinu nájdi 10 technických/SEO chýb len s bezplatnými nástrojmi (crawler free, PageSpeed, site: operátor, Rich Results Test, ručná kontrola). Trénuje rýchlosť diagnostiky na pohovory aj klientske call-y.',
    checklist: ['robots.txt + sitemap check', 'site: operátor — indexačný prehľad', 'PageSpeed / CWV rýchly test', 'Kontrola 404/redirect vzoriek', 'Title/description vzorka', 'Mobilná kontrola', '10 chýb zapísaných s dôkazom', 'Každá chyba má návrh riešenia'] },
  { id: 'proj-localseo', name: 'Lokálne SEO stratégia', module: 'gbp', icon: 'map', xp: 250,
    goal: 'Kompletná lokálna stratégia pre firmu s viac pobočkami.',
    brief: 'Model: firma s 3 pobočkami v rôznych mestách. Navrhni: štruktúru GBP profilov, location pages s LocalBusiness schema, citačný plán, geo-grid meranie, review playbook per pobočka a mesačný reporting. Výstup: stratégia škálovateľnej lokálnej prítomnosti.',
    checklist: ['Štruktúra profilov a naming', 'Návrh 1 vzorovej location page', 'LocalBusiness schema (JSON-LD) napísaná', 'Citačný plán (10+ zdrojov)', 'Geo-grid merací plán', 'Review playbook so SLA', 'Šablóna mesačného reportu per pobočka'] },
];

/* ── SLOVNÍK POJMOV ──────────────────────────────────────────────
   simple: vysvetlenie „ľudskou rečou" · tech: technická definícia */
DATA.glossary = [
  { term: 'CTR', cat: 'ads', simple: 'Koľko percent ľudí, ktorí videli reklamu/výsledok, naň kliklo.', tech: 'Click-Through Rate = kliky ÷ impresie × 100. Kľúčová metrika relevancie reklamy aj organického snippetu; vstupuje do Quality Score ako expected CTR.' },
  { term: 'CPC', cat: 'ads', simple: 'Cena, ktorú zaplatíš za jeden klik na reklamu.', tech: 'Cost-Per-Click. Max CPC = tvoja maximálna ponuka; actual CPC = reálne strhnutá suma (stačí prekonať Ad Rank konkurenta pod tebou).' },
  { term: 'CPA', cat: 'ads', simple: 'Koľko ťa stojí získanie jedného zákazníka/konverzie.', tech: 'Cost-Per-Acquisition = náklady ÷ konverzie. Target CPA je smart bidding stratégia optimalizujúca na cieľovú hodnotu CPA.' },
  { term: 'ROAS', cat: 'ads', simple: 'Koľko eur tržieb ti prinesie 1 euro do reklamy.', tech: 'Return On Ad Spend = hodnota konverzií ÷ náklady. Break-even ROAS = 1/marža. Target ROAS je value-based bidding stratégia.' },
  { term: 'Conversion (konverzia)', cat: 'ads', simple: 'Akcia, ktorú od návštevníka chceš — nákup, formulár, hovor.', tech: 'Meraná akcia definovaná konverznou akciou v Ads/GA4. Delí sa na primary (riadi bidding) a secondary (pozorovanie). Môže mať statickú alebo dynamickú hodnotu.' },
  { term: 'Quality Score', cat: 'ads', simple: 'Známka 1–10, ako kvalitná je tvoja reklama pre dané kľúčové slovo. Lepšia známka = nižšie ceny.', tech: 'Diagnostické skóre z 3 komponentov: expected CTR, ad relevance, landing page experience. Reálna aukcia používa jemnejšie real-time signály kvality.' },
  { term: 'Ad Rank', cat: 'ads', simple: 'Skóre, ktoré rozhoduje o poradí reklám v aukcii.', tech: '≈ bid × kvalita + očakávaný vplyv assets + kontext aukcie a prahy. Prepočítava sa v každej aukcii nanovo.' },
  { term: 'Impression Share', cat: 'ads', simple: 'Z koľkých percent možných zobrazení si sa reálne zobrazil.', tech: 'Impresie ÷ celkové dostupné impresie. Stratený IS sa delí na budget (málo peňazí) a rank (slabý Ad Rank). Target Impression Share je bidding stratégia.' },
  { term: 'Auction (aukcia)', cat: 'ads', simple: 'Bleskový „konkurz" reklám pri každom vyhľadávaní — vyhráva najlepšia kombinácia ceny a kvality.', tech: 'GSP aukcia upravená o kvalitu: platíš minimum potrebné na prekonanie Ad Ranku nasledujúceho inzerenta. Prebiehajú miliardy denne.' },
  { term: 'Match type', cat: 'ads', simple: 'Nastavenie, ako voľne sa má kľúčové slovo párovať s tým, čo ľudia píšu do Googlu.', tech: 'Broad (významové rozšírenie), phrase ("…" — zahŕňa význam), exact ([…] — zhodný zámer vrátane variantov). Negatívne zhody fungujú doslovnejšie.' },
  { term: 'Negative keyword', cat: 'ads', simple: 'Slovo, pri ktorom sa tvoja reklama NEMÁ zobraziť.', tech: 'Vylučujúce kritérium na úrovni skupiny/kampane/zdieľaného zoznamu. Nepoužíva významové rozšírenie — synonymá a tvary slov treba pridať explicitne.' },
  { term: 'RSA', cat: 'ads', simple: 'Moderná textová reklama — dodáš veľa nadpisov a Google z nich skladá najlepšie kombinácie.', tech: 'Responsive Search Ad: až 15 nadpisov (30 zn.) + 4 popisy (90 zn.), zobrazuje do 3+2. Ad Strength hodnotí kvalitu vstupov; pinning obmedzuje rotáciu.' },
  { term: 'Smart Bidding', cat: 'ads', simple: 'Google nastavuje ponuky za teba pomocou AI tak, aby si dosiahol svoj cieľ (cena za zákazníka, návratnosť…).', tech: 'Aukčné real-time strojové učenie: tCPA, tROAS, Max Conversions/Value. Vyžaduje konverzné dáta; learning fáza po zmenách; signály: zariadenie, čas, publikum, lokalita…' },
  { term: 'Performance Max', cat: 'ads', simple: 'Jedna kampaň, ktorá beží všade (vyhľadávanie, YouTube, mapy, Gmail…) a Google ju riadi sám.', tech: 'Cieľová kampaň naprieč všetkými inventármi. Vstupy: asset groups, audience signals, feed, ciele. Exact match Search keyword má pred PMax prioritu pri zhode dopytu.' },
  { term: 'Remarketing', cat: 'ads', simple: 'Reklama pre ľudí, ktorí už boli na tvojom webe — pripomínaš sa im.', tech: 'Cielenie na zoznamy z tagu/CRM/YouTube. Segmentácia podľa správania a recency; dynamický remarketing spája zoznamy s produktovým feedom.' },
  { term: 'Customer Match', cat: 'ads', simple: 'Nahráš zoznam e-mailov svojich zákazníkov a Google im (po spárovaní) vie zobrazovať tvoje reklamy.', tech: 'First-party cielenie: hashované kontakty párované s Google účtami. Základ privacy-friendly stratégií a lookalike segmentov v Demand Gen.' },
  { term: 'GCLID', cat: 'ads', simple: 'Neviditeľný kód v URL, ktorý spája klik na reklamu s neskoršou konverziou.', tech: 'Google Click ID — parameter pripájaný k URL pri kliku. Umožňuje offline conversion import: CRM pošle GCLID + výsledok späť do Ads.' },
  { term: 'Consent Mode', cat: 'ads', simple: 'Systém, ktorý rešpektuje cookie súhlas návštevníka a pri odmietnutí Google chýbajúce dáta dopočíta.', tech: 'v2 signály: ad_storage, ad_user_data, ad_personalization, analytics_storage. Bez súhlasu cookieless pingy + konverzné modelovanie. Povinné pre EÚ merania a remarketing od 3/2024.' },
  { term: 'Local Pack', cat: 'gbp', simple: 'Blok s mapou a 3 firmami, ktorý Google ukazuje pri hľadaní miestnych služieb.', tech: 'SERP feature pre dopyty s lokálnym zámerom; poradie určuje relevance/distance/prominence. Rozšírený zoznam = Local Finder. Justifications zvyšujú CTR.' },
  { term: 'Knowledge Panel', cat: 'gbp', simple: 'Veľká vizitka firmy vpravo vo výsledkoch, keď niekto hľadá firmu podľa mena.', tech: 'Panel generovaný z GBP + Knowledge Graph pri brandových dopytoch: recenzie, fotky, posts, Q&A, atribúty, CTA (volať/trasa/web).' },
  { term: 'NAP', cat: 'gbp', simple: 'Názov, adresa a telefón firmy — musia byť všade na internete rovnaké.', tech: 'Name, Address, Phone. Konzistencia naprieč profilom, webom a citáciami je dôverový signál lokálneho algoritmu; nekonzistencia oslabuje entity matching.' },
  { term: 'Citácia (citation)', cat: 'gbp', simple: 'Zmienka o firme (s údajmi) na inom webe — napríklad v katalógu firiem.', tech: 'Štruktúrované (katalógy) a neštruktúrované (články) výskyty NAP. Budujú prominence; kvalita a konzistencia > kvantita.' },
  { term: 'Service Area Business', cat: 'gbp', simple: 'Firma, ktorá jazdí za zákazníkmi (inštalatér, kuriér) — na mape nemá viditeľnú adresu.', tech: 'SAB: adresa skrytá, nastavené oblasti pôsobenia. Verifikácia dokazuje reálne podnikanie (vozidlo, náradie, dokumenty).' },
  { term: 'Review gating', cat: 'gbp', simple: 'Zakázaný trik: spokojných posielaš na Google recenzie a nespokojných do skrytého formulára.', tech: 'Selektívne žiadanie recenzií podľa sentimentu — výslovne zakázané pravidlami Googlu; riziko odstránenia recenzií a postihu profilu.' },
  { term: 'Justifications', cat: 'gbp', simple: 'Malé texty pri firme vo výsledkoch („Na webe uvádza…"), ktorými Google vysvetľuje, prečo firmu ukazuje.', tech: 'Automatické úryvky z webu, recenzií, services/products a posts párované s dopytom. Nepriamo optimalizovateľné obsahom.' },
  { term: 'Crawl', cat: 'gsc', simple: 'Proces, pri ktorom Google robot „prechádza" internet a sťahuje si stránky.', tech: 'Googlebot (mobile-first) objavuje a sťahuje URL podľa crawl budgetu (capacity × demand). Riadi sa robots.txt; monitoring v Crawl stats.' },
  { term: 'Indexácia', cat: 'gsc', simple: 'Zaradenie stránky do „knižnice" Googlu, z ktorej sa skladajú výsledky vyhľadávania.', tech: 'Po renderingu a kanonizácii Google selektívne ukladá URL do indexu. Nie je nároková; riadená kvalitou, noindex, canonical.' },
  { term: 'Canonical', cat: 'gsc', simple: 'Značka, ktorou webu povieš: „toto je hlavná verzia tejto stránky" (keď existuje viac podobných).', tech: 'rel=canonical je hint pre kanonizáciu duplicitných URL. Google-selected canonical môže deklaráciu prehlasovať podľa signálov (odkazy, sitemap, redirecty).' },
  { term: 'Coverage / Page indexing', cat: 'gsc', simple: 'Report v Search Console, ktorý ukazuje, ktoré stránky Google zaradil a ktoré nie — a prečo.', tech: 'Stavy: indexed, crawled/discovered not indexed, duplicate, blocked, soft 404, redirect… Pracuje sa s trendmi a validáciou opráv.' },
  { term: 'Soft 404', cat: 'gsc', simple: 'Stránka, ktorá tvrdí „všetko OK", ale v skutočnosti je prázdna — Google ju ignoruje.', tech: 'HTTP 200 s obsahom vyhodnoteným ako chýbajúci/bezcenný (prázdne kategórie, chybové texty, irelevantné redirecty). Rieši sa obsahom, korektným 404/410 alebo 301.' },
  { term: 'Sitemap', cat: 'gsc', simple: 'Zoznam stránok webu, ktorý odovzdáš Googlu, aby o nich vedel.', tech: 'XML súbor (max 50k URL/50 MB), len kanonické 200 URL; lastmod používaný, priority/changefreq ignorované. Odosiela sa v GSC + referencia v robots.txt.' },
  { term: 'Core Web Vitals', cat: 'gsc', simple: 'Tri merania, ako rýchlo a príjemne sa tvoj web správa: rýchlosť, odozva a „neposkakovanie".', tech: 'LCP ≤2,5 s, INP ≤200 ms, CLS ≤0,1 na 75. percentile field dát (CrUX, 28-dňové okno). Mierny ranking signál, silný UX/konverzný faktor.' },
  { term: 'Manual Action', cat: 'gsc', simple: 'Ručný trest od Googlu za porušenie pravidiel — web padá z výsledkov, kým chybu neopravíš.', tech: 'Penalizácia od reviewera (spam policies): unnatural links, thin content, cloaking… Náprava + reconsideration request. Odlíš od algoritmických prepadov.' },
  { term: 'Average Position', cat: 'gsc', simple: 'Priemerné umiestnenie tvojho webu vo výsledkoch pre daný dopyt.', tech: 'Priemer najvyššej pozície pri každej impresii. Interpretovať vždy s impresiami (nové dopyty „zhoršujú" priemer). Per-web agregát je takmer bezcenný.' },
  { term: 'Impression', cat: 'gsc', simple: 'Jedno zobrazenie tvojho webu/reklamy vo výsledkoch — aj keď naň nikto neklikol.', tech: 'V GSC sa počíta pri zobrazení stránky SERP obsahujúcej výsledok (bez nutnosti viditeľnosti vo viewporte pri klasických výsledkoch).' },
  { term: 'SERP', cat: 'gsc', simple: 'Stránka s výsledkami vyhľadávania — to, čo vidíš po zadaní dopytu.', tech: 'Search Engine Results Page: organické výsledky, Ads, Local Pack, featured snippets, AI Overviews, obrázky… Zloženie závisí od intentu dopytu.' },
  { term: 'Schema / Structured Data', cat: 'gsc', simple: 'Neviditeľné značky v kóde, ktoré Googlu presne povedia, čo je na stránke (produkt, recept, firma…).', tech: 'Slovník schema.org v JSON-LD. Odomyká rich results; musí zodpovedať viditeľnému obsahu. Validácia: Rich Results Test, GSC Enhancements.' },
  { term: 'Redirect 301/302', cat: 'gsc', simple: 'Presmerovanie: 301 = „presťahovali sme sa natrvalo", 302 = „sme tu len dočasne inde".', tech: '301 prenáša signály na cieľ; 302/307 ich drží na zdroji. Max 1 skok, relevantný cieľ (masové redirecty na homepage = soft 404).' },
  { term: 'Anchor text', cat: 'gsc', simple: 'Klikateľný text odkazu — modré slová, na ktoré klikáš.', tech: 'Textový obsah <a> elementu; relevančný signál pre cieľovú stránku. Profil anchorov sa hodnotí v rámci prirodzenosti odkazového profilu.' },
  { term: 'LTV', cat: 'ads', simple: 'Koľko peňazí ti zákazník prinesie za celý čas, čo u teba nakupuje.', tech: 'Lifetime Value. Určuje udržateľné akvizičné CPA — firmy s vysokým LTV si môžu dovoliť „stratovú" prvú objednávku a vyhrávajú aukcie.' },
  { term: 'Attribution (atribúcia)', cat: 'ads', simple: 'Rozhodovanie, ktorá reklama dostane „zásluhu" za nákup, keď ich zákazník videl viac.', tech: 'Data-driven attribution (default) frakčne deľí kredit podľa príspevku kontaktov v konverzných cestách. Nemeria inkrementalitu — na tú slúžia experimenty.' },
];

/* ── FLASHCARDS (spaced repetition — SM-2 zjednodušený) ─────────── */
DATA.flashcards = [
  { id: 'fc1', mod: 'gbp', q: 'Tri oficiálne piliere lokálneho rankingu?', a: 'Relevance (relevantnosť), Distance (vzdialenosť), Prominence (významnosť).' },
  { id: 'fc2', mod: 'gbp', q: 'Najsilnejší relevančný signál GBP profilu?', a: 'Primárna kategória.' },
  { id: 'fc3', mod: 'gbp', q: 'Koľko kategórií môže mať GBP profil?', a: '1 primárna + max 9 sekundárnych.' },
  { id: 'fc4', mod: 'gbp', q: 'Čo je review gating a je povolený?', a: 'Filtrovanie — spokojní na Google, nespokojní do formulára. Výslovne ZAKÁZANÝ.' },
  { id: 'fc5', mod: 'gbp', q: 'NAP znamená…', a: 'Name, Address, Phone — musí byť konzistentné všade na internete.' },
  { id: 'fc6', mod: 'gbp', q: 'Formulár na nahlásenie podvodných profilov na Maps?', a: 'Business Redressal Complaint Form.' },
  { id: 'fc7', mod: 'gbp', q: 'Ako dlho uchováva GBP Performance dáta?', a: 'Len ~6 mesiacov — preto sa mesačne exportujú.' },
  { id: 'fc8', mod: 'gbp', q: '4A framework odpovede na negatívnu recenziu?', a: 'Acknowledge → Apologize → Act → Aside (presunúť riešenie offline).' },
  { id: 'fc9', mod: 'gbp', q: 'Čo sú justifications?', a: 'Úryvky pri výsledku („Na webe uvádza…", „V recenzii sa spomína…"), ktorými Google zdôvodňuje zobrazenie firmy.' },
  { id: 'fc10', mod: 'gbp', q: 'Service Area Business (SAB)?', a: 'Firma poskytujúca služby u zákazníka — adresa skrytá, nastavené oblasti pôsobenia.' },
  { id: 'fc11', mod: 'gsc', q: 'Tri fázy cesty stránky do výsledkov?', a: 'Crawling → Indexing (rendering + kanonizácia) → Serving.' },
  { id: 'fc12', mod: 'gsc', q: 'robots.txt riadi crawling alebo indexáciu?', a: 'Crawling! Na de-indexáciu slúži noindex — a stránka nesmie byť zablokovaná, inak Google noindex neuvidí.' },
  { id: 'fc13', mod: 'gsc', q: 'Limity XML sitemap?', a: '50 000 URL / 50 MB na súbor; len kanonické 200 URL; lastmod sa používa, priority/changefreq nie.' },
  { id: 'fc14', mod: 'gsc', q: 'Rozdiel „Crawled" vs. „Discovered — currently not indexed"?', a: 'Crawled = stiahnutá, ale nezaradená (kvalita). Discovered = Google o nej vie, ešte ju nestiahol (priorita/budget).' },
  { id: 'fc15', mod: 'gsc', q: 'Canonical tag je príkaz alebo hint?', a: 'Hint — Google ho môže prehlasovať (Google-selected canonical) podľa ostatných signálov.' },
  { id: 'fc16', mod: 'gsc', q: '301 vs. 302?', a: '301 = trvalé, prenáša signály na cieľ. 302 = dočasné, signály zostávajú na zdroji.' },
  { id: 'fc17', mod: 'gsc', q: 'Čo je soft 404?', a: 'Stránka vracia 200, ale obsahovo je prázdna/bezcenná — Google ju klasifikuje ako chybu a neindexuje.' },
  { id: 'fc18', mod: 'gsc', q: 'Tri Core Web Vitals metriky a dobré hodnoty?', a: 'LCP ≤ 2,5 s · INP ≤ 200 ms · CLS ≤ 0,1 (75. percentil field dát).' },
  { id: 'fc19', mod: 'gsc', q: 'Koľko histórie má GSC Performance?', a: '16 mesiacov.' },
  { id: 'fc20', mod: 'gsc', q: 'Manual action vs. algoritmický prepad?', a: 'Manual action = správa v GSC + reconsideration request. Algoritmus = žiaden záznam, rieši sa kvalitou.' },
  { id: 'fc21', mod: 'gsc', q: 'Striking distance dopyty?', a: 'Pozície ~5–20 s impresiami — malé zlepšenie = veľký rast klikov. Filter v Performance reporte.' },
  { id: 'fc22', mod: 'gsc', q: 'Čo je kanibalizácia kľúčových slov?', a: 'Viac vlastných stránok súťaží o rovnaký dopyt a delí si signály. Riešenie: konsolidácia + 301, rozlíšenie intentu.' },
  { id: 'fc23', mod: 'ads', q: 'Vzorec Ad Rank?', a: '≈ max CPC bid × Quality Score + očakávaný vplyv assets + kontext/prahy aukcie.' },
  { id: 'fc24', mod: 'ads', q: 'Tri komponenty Quality Score?', a: 'Expected CTR · Ad Relevance · Landing Page Experience.' },
  { id: 'fc25', mod: 'ads', q: 'Zápisy match types?', a: 'broad (bez znakov) · "phrase" · [exact]. Všetky sú dnes významové.' },
  { id: 'fc26', mod: 'ads', q: 'Negatívne slová používajú synonymá?', a: 'NIE — blokujú (takmer) doslovne. Synonymá a tvary slov treba pridať manuálne.' },
  { id: 'fc27', mod: 'ads', q: 'RSA limity?', a: 'Až 15 nadpisov (30 znakov) + 4 popisy (90 znakov); zobrazia sa max 3+2.' },
  { id: 'fc28', mod: 'ads', q: 'Break-even ROAS pri marži 25 %?', a: '1 / 0,25 = 400 %. Pod touto hodnotou kampaň prerába.' },
  { id: 'fc29', mod: 'ads', q: 'Kedy prejsť na tCPA?', a: 'Po nazbieraní ~30–50 konverzií; cieľ nastaviť blízko historického CPA a uťahovať po 10–15 %.' },
  { id: 'fc30', mod: 'ads', q: 'Čo je learning fáza?', a: '~1–2 týždne po zmene bidding stratégie/cieľa — výkon kolíše, nehodnotiť a nemeniť.' },
  { id: 'fc31', mod: 'ads', q: 'Audience signal v PMax je obmedzenie?', a: 'Nie — je to nápoveda. Systém môže cieliť aj mimo signálu podľa pravdepodobnosti konverzie.' },
  { id: 'fc32', mod: 'ads', q: 'Prečo vylúčiť brand z PMax?', a: 'Aby si nepripisoval lacné brand konverzie, ktoré by prišli aj tak — skresľoval by výkon.' },
  { id: 'fc33', mod: 'ads', q: 'Shopping kampane cielia cez kľúčové slová?', a: 'Nie — cez obsah produktového feedu (najmä title). Feed optimalizácia = „SEO Shoppingu".' },
  { id: 'fc34', mod: 'ads', q: 'Kedy platíš pri skippable in-stream (CPV)?', a: 'Pri 30 s zhliadnutí (alebo celom kratšom videu) alebo interakcii. Preskočenie do 30 s = zadarmo.' },
  { id: 'fc35', mod: 'ads', q: 'Default atribučný model?', a: 'Data-driven attribution — frakčný kredit podľa skutočného príspevku kontaktov.' },
  { id: 'fc36', mod: 'ads', q: 'Primary vs. secondary konverzie?', a: 'Primary riadia smart bidding; secondary sú len na pozorovanie. Mikrokonverzie nikdy nie primary.' },
  { id: 'fc37', mod: 'ads', q: 'Consent Mode v2 — čo robí bez súhlasu?', a: 'Tagy posielajú cookieless pingy a Google konverzie modeluje. Povinný pre EÚ od 3/2024.' },
  { id: 'fc38', mod: 'ads', q: 'Targeting vs. Observation?', a: 'Targeting zužuje zobrazovanie na publikum; Observation len meria výkon segmentu bez obmedzenia dosahu.' },
  { id: 'fc39', mod: 'ads', q: 'Podmienky certifikácie Google Ads?', a: 'Skillshop, zadarmo, ~50 otázok / 75 min, 80 % na absolvovanie, platnosť 12 mesiacov.' },
  { id: 'fc40', mod: 'ads', q: '„Limited by budget" pri dobrom CPA znamená?', a: 'Rastová príležitosť — kampaň by efektívne minula viac; presuň/zvýš rozpočet.' },
];

/* ── KARIÉRNY PLÁN ───────────────────────────────────────────────── */
DATA.career = {
  positions: [
    { title: 'Freelancer — správa GBP profilov', level: 'Junior', salary: '200–500 € / klient / kvartál', needs: ['gbp'],
      desc: 'Vstupná služba s najnižšou bariérou: audit + optimalizácia + mesačná správa profilov lokálnych firiem. Ideálne prvé platené zákazky popri kurze.' },
    { title: 'PPC Junior Specialist (agentúra)', level: 'Junior', salary: '1 100 – 1 500 € / mes. (SK)', needs: ['ads'],
      desc: 'Správa kampaní pod vedením seniora: search terms, reklamy, reporty. Vyžaduje: Search certifikácia + základné portfólio. Najbežnejší vstup do odvetvia.' },
    { title: 'SEO Specialist', level: 'Junior–Medior', salary: '1 300 – 2 000 € / mes. (SK)', needs: ['gsc', 'gbp'],
      desc: 'Technické SEO, audity, obsahová stratégia. GSC modul + prax z auditov je presne tento skillset; GBP pridáva lokálnu špecializáciu.' },
    { title: 'PPC Specialist / Account Manager', level: 'Medior', salary: '1 600 – 2 500 € / mes. (SK)', needs: ['ads', 'gsc'],
      desc: 'Samostatná správa klientskych účtov, stratégia, komunikácia s klientmi. Vyžaduje 1–2 roky praxe alebo silné portfólio + viaceré certifikácie.' },
    { title: 'Digital Marketing Freelancer (full-stack)', level: 'Medior–Senior', salary: '30 – 70 € / hod.', needs: ['gbp', 'gsc', 'ads'],
      desc: 'Kombinácia všetkých troch oblastí = kompletná služba pre SME klientov: viditeľnosť (GBP), web (GSC/SEO), výkon (Ads). Najvyššia marža, plná sloboda.' },
    { title: 'Performance Marketing Manager', level: 'Senior', salary: '2 500 – 4 000+ € / mes. (SK)', needs: ['ads', 'gsc'],
      desc: 'Stratégia, rozpočty, tím, mix kanálov, inkrementalita. Cesta: 3+ roky praxe, preukázateľné výsledky, silná analytika a biznis myslenie.' },
  ],
  steps: [
    'Dokonči všetky 3 moduly a záverečné projekty (portfólio 3 dokumentov)',
    'Zlož Search certifikáciu + Measurement certifikáciu na Skillshop',
    'Sprav zadarmo/za referenciu 2–3 reálne zákazky (známi, lokálne firmy)',
    'Vytvor si jednoduchý web/LinkedIn s portfóliom a výsledkami',
    'Uchádzaj sa o junior pozície v agentúrach ALEBO oslov 20 lokálnych firiem s ponukou auditu',
    'Po 6–12 mesiacoch praxe: špecializuj sa (e-commerce / lead-gen / lokál) a zvyšuj sadzby',
  ],
  extra: [
    'Google Analytics 4 — meranie do hĺbky (Skillshop certifikácia)',
    'Google Tag Manager — technická nadstavba merania',
    'Looker Studio — reporting a dashboardy',
    'Meta Ads — druhá platforma pre full-stack profil',
    'CRO / landing pages — konverzná optimalizácia zvyšuje hodnotu všetkých kampaní',
    'AI nástroje v marketingu — automatizácia rutiny, generovanie kreatív',
  ],
};

/* ── ACHIEVEMENTY ────────────────────────────────────────────────── */
DATA.achievements = [
  { id: 'first-lesson', name: 'Prvý krok', desc: 'Dokonč prvú lekciu', icon: '🎯', check: s => Object.keys(s.completedLessons).length >= 1 },
  { id: 'ten-lessons', name: 'Rozbehnutý', desc: 'Dokonč 10 lekcií', icon: '🚀', check: s => Object.keys(s.completedLessons).length >= 10 },
  { id: 'thirty-lessons', name: 'Maratónec', desc: 'Dokonč 30 lekcií', icon: '🏃', check: s => Object.keys(s.completedLessons).length >= 30 },
  { id: 'all-lessons', name: 'Absolvent', desc: 'Dokonč všetky lekcie', icon: '🎓', check: s => Object.keys(s.completedLessons).length >= App.totalLessons() },
  { id: 'first-quiz', name: 'Otestovaný', desc: 'Absolvuj prvý kvíz', icon: '📝', check: s => Object.keys(s.quizResults).length >= 1 },
  { id: 'perfect-quiz', name: 'Perfekcionista', desc: 'Kvíz na 100 %', icon: '💯', check: s => Object.values(s.quizResults).some(r => r.score === r.total && r.total >= 5) },
  { id: 'module-test', name: 'Modulový majster', desc: 'Zlož modulový test na 80 %+', icon: '🏅', check: s => s.testHistory.some(t => t.type === 'module' && t.score / t.total >= 0.8) },
  { id: 'final-test', name: 'Finálna skúška', desc: 'Zlož záverečný test (100 otázok) na 80 %+', icon: '👑', check: s => s.testHistory.some(t => t.type === 'final' && t.score / t.total >= 0.8) },
  { id: 'streak-3', name: 'Zohrievanie', desc: '3-dňová séria učenia', icon: '🔥', check: s => s.streak.count >= 3 },
  { id: 'streak-7', name: 'Týždeň v ohni', desc: '7-dňová séria učenia', icon: '🔥', check: s => s.streak.count >= 7 },
  { id: 'streak-30', name: 'Nezastaviteľný', desc: '30-dňová séria učenia', icon: '☄️', check: s => s.streak.count >= 30 },
  { id: 'first-cert', name: 'Certifikovaný', desc: 'Označ prvú certifikáciu ako získanú', icon: '📜', check: s => Object.values(s.certs).filter(c => c.done).length >= 1 },
  { id: 'three-certs', name: 'Zberateľ certifikátov', desc: 'Získaj 3 certifikácie', icon: '🏆', check: s => Object.values(s.certs).filter(c => c.done).length >= 3 },
  { id: 'first-project', name: 'Praktik', desc: 'Dokonč prvý projekt', icon: '🛠️', check: s => Object.values(s.projects).filter(p => p.status === 'done').length >= 1 },
  { id: 'all-projects', name: 'Portfólio hotové', desc: 'Dokonč všetky projekty', icon: '💼', check: s => Object.values(s.projects).filter(p => p.status === 'done').length >= DATA.projects.length },
  { id: 'flash-50', name: 'Kartičkár', desc: 'Zopakuj 50 flashcards', icon: '🃏', check: s => (s.fcReviews || 0) >= 50 },
  { id: 'xp-1000', name: 'Tisícka', desc: 'Získaj 1 000 XP', icon: '⚡', check: s => s.xp >= 1000 },
  { id: 'xp-5000', name: 'Powerhouse', desc: 'Získaj 5 000 XP', icon: '🌟', check: s => s.xp >= 5000 },
  { id: 'module-gbp', name: 'GBP Expert', desc: 'Dokonč modul Google Business Profile', icon: '📍', check: s => App.moduleProgress('gbp') >= 100 },
  { id: 'module-gsc', name: 'GSC Expert', desc: 'Dokonč modul Search Console', icon: '🔍', check: s => App.moduleProgress('gsc') >= 100 },
  { id: 'module-ads', name: 'Ads Expert', desc: 'Dokonč modul Google Ads', icon: '📣', check: s => App.moduleProgress('ads') >= 100 },
];

/* ── AI MENTOR: scenáre simulácie klienta ────────────────────────── */
DATA.clientScenarios = [
  { id: 'sc1', name: 'Majiteľ reštaurácie — prázdne stoly', mod: 'gbp',
    intro: 'Dobrý deň… Mám taliansku reštauráciu v centre, 15 rokov. Posledné 2 roky cítim, že nové tváre nechodia — vraj nás ľudia „nevedia nájsť na mape". Konkurencia oproti má plno. Čo mi viete povedať?',
    hints: ['Opýtaj sa na stav profilu (claimnutý? recenzie? fotky?)', 'Vysvetli Local Pack a prečo je konkurencia vyššie', 'Navrhni audit ako prvý krok', 'Nastav reálne očakávania (recenzie a optimalizácia = týždne, nie dni)'],
    good: ['audit', 'recenz', 'kategó', 'fotk', 'profil', 'local pack', 'konkurenc'],
    reply: 'To znie rozumne. A koľko by ma to stálo a kedy uvidím výsledky? Sused vravel, že jemu ktosi sľúbil prvé miesto do týždňa…',
    hints2: ['Vysvetli, prečo „prvé miesto do týždňa" je červená vlajka (nikto negarantuje ranking)', 'Uveď reálny časový rámec (6–12 týždňov viditeľné zlepšenie)', 'Cenu ukotvi v hodnote (1 nový stôl denne = X € mesačne)'],
    good2: ['negarant', 'nikto nemôže', 'týžd', 'mesiac', 'hodnot', 'červen', 'sľub', 'realis'],
    end: 'Dobre, to mi dáva zmysel. Ozvite sa mi s návrhom auditu. — KONIEC SIMULÁCIE. Zvládol si: nastaviť očakávania, odmietnuť nereálne sľuby a ukotviť cenu v hodnote. Presne takto vyzerá profesionálny prvý rozhovor.' },
  { id: 'sc2', name: 'E-shop — „Ads nefungujú"', mod: 'ads',
    intro: 'Ahojte. Máme e-shop so športovým oblečením. Minuli sme za 3 mesiace 4 000 € na Google Ads a „nič z toho". Kampane nám robil brat kamaráta. Chcem to celé vypnúť. Presvedčte ma, prečo nie.',
    hints: ['Neobhajuj Ads — najprv diagnostikuj: ako sa meria „nič"? Je konverzné meranie?', 'Opýtaj sa na maržu a break-even ROAS', 'Navrhni audit účtu pred akýmkoľvek rozhodnutím'],
    good: ['meranie', 'konverz', 'audit', 'marž', 'roas', 'dáta', 'merať'],
    reply: 'Meranie… no, vidíme kliky. Či sa z nich nakupuje, presne nevieme. Marža je okolo 40 %. Aha, a ešte — všetky kampane vraj bežali na „maximalizáciu klikov".',
    hints2: ['Pomenuj 2 konkrétne nálezy: chýbajúce konverzné meranie + zlá bidding stratégia', 'Vysvetli break-even ROAS pri 40 % marži (250 %)', 'Navrhni plán: meranie → rekonštrukcia → 2 mesiace vyhodnotenie'],
    good2: ['250', 'break', 'tROAS', 'troas', 'meranie', 'tag', 'najprv', 'plán', 'rekonštru'],
    end: 'Hm. Takže problém možno nebol v Google, ale v tom, ako to bolo nastavené… Dobre, spravte audit. — KONIEC SIMULÁCIE. Kľúčový moment: nezačal si obhajobou platformy, ale diagnostikou merania — to odlišuje profesionála od predajcu.' },
  { id: 'sc3', name: 'Firemný web — prepad návštevnosti', mod: 'gsc',
    intro: 'Dobrý deň, sme výrobná firma. Pred mesiacom nám spadla návštevnosť z Googlu o 60 % zo dňa na deň. IT hovorí, že „nič nemenili". Marketing hovorí, že to je „algoritmus". Kto má pravdu a čo máme robiť?',
    hints: ['Pýtaj si prístup do GSC — bez dát sa nedá diagnostikovať', 'Over: manual actions? presný dátum prepadu? celý web či časť?', 'Spýtaj sa na zmeny okolo toho dátumu (redizajn, migrácia, certifikát…)'],
    good: ['gsc', 'search console', 'prístup', 'manual', 'dátum', 'dáta', 'kedy presne', 'čast'],
    reply: 'Prístup vám dáme. Teraz si spomínam — IT vtedy „len presúvalo web na nový server a novú šablónu". Ale vraj sa nič nemenilo, len dizajn. V Search Console je vraj veľa červených hlásení o „presmerovaniach" a „404".',
    hints2: ['Pomenuj pravdepodobnú príčinu: migrácia bez redirect mapy', 'Vysvetli postup záchrany: mapa starých URL → 301 redirecty → validácia v GSC', 'Nastav očakávania návratu (týždne až mesiace)'],
    good2: ['redirect', '301', 'migrác', 'mapa', 'url', 'presmerovan', 'validá'],
    end: 'Takže „nič sme nemenili" znamenalo novú šablónu a nové URL… Rozumiem. Pustite sa do toho. — KONIEC SIMULÁCIE. Diagnóza cez dáta namiesto dohadov + znalosť migračného playbooku = presne to, za čo si klienti platia.' },
];
</script>
